blank_issues_enabled: false
contact_links:
  - name: ❓ GitHub Discussions
    url: https://github.com/PiBOH-EDU/tcr-notes/discussions/
    about: Usa questo spazio per Q&A e idee generali che non sono ancora feature request.
